[project]
name = "pipiline-etl"
version = "0.1.0"
description = ""
authors = [
    {name = "João Henrique Sgobero",email = "joao.sgobero@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel (>=7.2.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
